/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MetaRouter } from "./MetaRouter";
export type { MetaRouterGateway } from "./MetaRouterGateway";
