/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace MetaRouteStructs {
  export type MetaMintTransactionStruct = {
    stableBridgingFee: BigNumberish;
    amount: BigNumberish;
    crossChainID: BytesLike;
    externalID: BytesLike;
    tokenReal: AddressLike;
    chainID: BigNumberish;
    to: AddressLike;
    swapTokens: AddressLike[];
    secondDexRouter: AddressLike;
    secondSwapCalldata: BytesLike;
    finalReceiveSide: AddressLike;
    finalCalldata: BytesLike;
    finalOffset: BigNumberish;
  };

  export type MetaMintTransactionStructOutput = [
    stableBridgingFee: bigint,
    amount: bigint,
    crossChainID: string,
    externalID: string,
    tokenReal: string,
    chainID: bigint,
    to: string,
    swapTokens: string[],
    secondDexRouter: string,
    secondSwapCalldata: string,
    finalReceiveSide: string,
    finalCalldata: string,
    finalOffset: bigint
  ] & {
    stableBridgingFee: bigint;
    amount: bigint;
    crossChainID: string;
    externalID: string;
    tokenReal: string;
    chainID: bigint;
    to: string;
    swapTokens: string[];
    secondDexRouter: string;
    secondSwapCalldata: string;
    finalReceiveSide: string;
    finalCalldata: string;
    finalOffset: bigint;
  };

  export type MetaMintTransactionBTCStruct = {
    stableBridgingFee: BigNumberish;
    amount: BigNumberish;
    serial: BigNumberish;
    crossChainID: BytesLike;
    externalID: BytesLike;
    tokenReal: AddressLike;
    chainID: BigNumberish;
    to: AddressLike;
    swapTokens: AddressLike[];
    secondDexRouter: AddressLike;
    secondSwapCalldata: BytesLike;
    finalReceiveSide: AddressLike;
    finalCalldata: BytesLike;
    finalOffset: BigNumberish;
  };

  export type MetaMintTransactionBTCStructOutput = [
    stableBridgingFee: bigint,
    amount: bigint,
    serial: bigint,
    crossChainID: string,
    externalID: string,
    tokenReal: string,
    chainID: bigint,
    to: string,
    swapTokens: string[],
    secondDexRouter: string,
    secondSwapCalldata: string,
    finalReceiveSide: string,
    finalCalldata: string,
    finalOffset: bigint
  ] & {
    stableBridgingFee: bigint;
    amount: bigint;
    serial: bigint;
    crossChainID: string;
    externalID: string;
    tokenReal: string;
    chainID: bigint;
    to: string;
    swapTokens: string[];
    secondDexRouter: string;
    secondSwapCalldata: string;
    finalReceiveSide: string;
    finalCalldata: string;
    finalOffset: bigint;
  };

  export type MetaRouteTransactionStruct = {
    firstSwapCalldata: BytesLike;
    secondSwapCalldata: BytesLike;
    approvedTokens: AddressLike[];
    firstDexRouter: AddressLike;
    secondDexRouter: AddressLike;
    amount: BigNumberish;
    nativeIn: boolean;
    relayRecipient: AddressLike;
    otherSideCalldata: BytesLike;
  };

  export type MetaRouteTransactionStructOutput = [
    firstSwapCalldata: string,
    secondSwapCalldata: string,
    approvedTokens: string[],
    firstDexRouter: string,
    secondDexRouter: string,
    amount: bigint,
    nativeIn: boolean,
    relayRecipient: string,
    otherSideCalldata: string
  ] & {
    firstSwapCalldata: string;
    secondSwapCalldata: string;
    approvedTokens: string[];
    firstDexRouter: string;
    secondDexRouter: string;
    amount: bigint;
    nativeIn: boolean;
    relayRecipient: string;
    otherSideCalldata: string;
  };
}

export interface MetaRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "externalCall"
      | "metaMintSwap"
      | "metaMintSwapBTC"
      | "metaRoute"
      | "metaRouterGateway"
      | "returnSwap"
      | "sendTransitToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransitTokenSent"): EventFragment;

  encodeFunctionData(
    functionFragment: "externalCall",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaMintSwap",
    values: [MetaRouteStructs.MetaMintTransactionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "metaMintSwapBTC",
    values: [MetaRouteStructs.MetaMintTransactionBTCStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "metaRoute",
    values: [MetaRouteStructs.MetaRouteTransactionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "metaRouterGateway",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnSwap",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendTransitToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "externalCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaMintSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaMintSwapBTC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "metaRoute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metaRouterGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "returnSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendTransitToken",
    data: BytesLike
  ): Result;
}

export namespace TransitTokenSentEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [to: string, amount: bigint, token: string];
  export interface OutputObject {
    to: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MetaRouter extends BaseContract {
  connect(runner?: ContractRunner | null): MetaRouter;
  waitForDeployment(): Promise<this>;

  interface: MetaRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  externalCall: TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _receiveSide: AddressLike,
      _calldata: BytesLike,
      _offset: BigNumberish,
      _to: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  metaMintSwap: TypedContractMethod<
    [_metaMintTransaction: MetaRouteStructs.MetaMintTransactionStruct],
    [void],
    "nonpayable"
  >;

  metaMintSwapBTC: TypedContractMethod<
    [_metaMintTransaction: MetaRouteStructs.MetaMintTransactionBTCStruct],
    [void],
    "nonpayable"
  >;

  metaRoute: TypedContractMethod<
    [_metarouteTransaction: MetaRouteStructs.MetaRouteTransactionStruct],
    [void],
    "payable"
  >;

  metaRouterGateway: TypedContractMethod<[], [string], "view">;

  returnSwap: TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _router: AddressLike,
      _swapCalldata: BytesLike,
      _burnToken: AddressLike,
      _synthesis: AddressLike,
      _burnCalldata: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  sendTransitToken: TypedContractMethod<
    [_token: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "externalCall"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _receiveSide: AddressLike,
      _calldata: BytesLike,
      _offset: BigNumberish,
      _to: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "metaMintSwap"
  ): TypedContractMethod<
    [_metaMintTransaction: MetaRouteStructs.MetaMintTransactionStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "metaMintSwapBTC"
  ): TypedContractMethod<
    [_metaMintTransaction: MetaRouteStructs.MetaMintTransactionBTCStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "metaRoute"
  ): TypedContractMethod<
    [_metarouteTransaction: MetaRouteStructs.MetaRouteTransactionStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "metaRouterGateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "returnSwap"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _amount: BigNumberish,
      _router: AddressLike,
      _swapCalldata: BytesLike,
      _burnToken: AddressLike,
      _synthesis: AddressLike,
      _burnCalldata: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendTransitToken"
  ): TypedContractMethod<
    [_token: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TransitTokenSent"
  ): TypedContractEvent<
    TransitTokenSentEvent.InputTuple,
    TransitTokenSentEvent.OutputTuple,
    TransitTokenSentEvent.OutputObject
  >;

  filters: {
    "TransitTokenSent(address,uint256,address)": TypedContractEvent<
      TransitTokenSentEvent.InputTuple,
      TransitTokenSentEvent.OutputTuple,
      TransitTokenSentEvent.OutputObject
    >;
    TransitTokenSent: TypedContractEvent<
      TransitTokenSentEvent.InputTuple,
      TransitTokenSentEvent.OutputTuple,
      TransitTokenSentEvent.OutputObject
    >;
  };
}
