/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBridge__factory } from "./IBridge__factory";
export { ISyntFabric__factory } from "./ISyntFabric__factory";
