/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISyntFabric,
  ISyntFabricInterface,
} from "../../../../../symbiosis-contracts/contracts/synth-core/interfaces/ISyntFabric";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_syntTokenAdr",
        type: "address",
      },
    ],
    name: "getRealRepresentation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_realTokenAdr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_chainID",
        type: "uint256",
      },
    ],
    name: "getSyntRepresentation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_stoken",
        type: "address",
      },
    ],
    name: "synthesize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_stoken",
        type: "address",
      },
    ],
    name: "unsynthesize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISyntFabric__factory {
  static readonly abi = _abi;
  static createInterface(): ISyntFabricInterface {
    return new Interface(_abi) as ISyntFabricInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISyntFabric {
    return new Contract(address, _abi, runner) as unknown as ISyntFabric;
  }
}
