/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridge from "./bridge";
export type { bridge };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as metarouter from "./metarouter";
export type { metarouter };
export type { SyntERC20 } from "./SyntERC20";
export type { SyntFabric } from "./SyntFabric";
export type { Synthesis } from "./Synthesis";
