/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "receiveRequestV2"
      | "transmitRequestBTC"
      | "transmitRequestV2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "receiveRequestV2",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transmitRequestBTC",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transmitRequestV2",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveRequestV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transmitRequestBTC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transmitRequestV2",
    data: BytesLike
  ): Result;
}

export interface IBridge extends BaseContract {
  connect(runner?: ContractRunner | null): IBridge;
  waitForDeployment(): Promise<this>;

  interface: IBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receiveRequestV2: TypedContractMethod<
    [_callData: BytesLike, _receiveSide: AddressLike],
    [void],
    "nonpayable"
  >;

  transmitRequestBTC: TypedContractMethod<
    [
      _from: AddressLike,
      _to: BytesLike,
      _amount: BigNumberish,
      _burnSerial: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transmitRequestV2: TypedContractMethod<
    [
      _callData: BytesLike,
      _receiveSide: AddressLike,
      _oppositeBridge: AddressLike,
      _chainId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receiveRequestV2"
  ): TypedContractMethod<
    [_callData: BytesLike, _receiveSide: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transmitRequestBTC"
  ): TypedContractMethod<
    [
      _from: AddressLike,
      _to: BytesLike,
      _amount: BigNumberish,
      _burnSerial: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transmitRequestV2"
  ): TypedContractMethod<
    [
      _callData: BytesLike,
      _receiveSide: AddressLike,
      _oppositeBridge: AddressLike,
      _chainId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
