/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ISyntFabricInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRealRepresentation"
      | "getSyntRepresentation"
      | "synthesize"
      | "unsynthesize"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRealRepresentation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSyntRepresentation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "synthesize",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsynthesize",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRealRepresentation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSyntRepresentation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "synthesize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsynthesize",
    data: BytesLike
  ): Result;
}

export interface ISyntFabric extends BaseContract {
  connect(runner?: ContractRunner | null): ISyntFabric;
  waitForDeployment(): Promise<this>;

  interface: ISyntFabricInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRealRepresentation: TypedContractMethod<
    [_syntTokenAdr: AddressLike],
    [string],
    "view"
  >;

  getSyntRepresentation: TypedContractMethod<
    [_realTokenAdr: AddressLike, _chainID: BigNumberish],
    [string],
    "view"
  >;

  synthesize: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _stoken: AddressLike],
    [void],
    "nonpayable"
  >;

  unsynthesize: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _stoken: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRealRepresentation"
  ): TypedContractMethod<[_syntTokenAdr: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSyntRepresentation"
  ): TypedContractMethod<
    [_realTokenAdr: AddressLike, _chainID: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "synthesize"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _stoken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unsynthesize"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _stoken: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
