/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RelayRecipientUpgradeable,
  RelayRecipientUpgradeableInterface,
} from "../../../../symbiosis-contracts/contracts/utils/RelayRecipientUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RelayRecipientUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): RelayRecipientUpgradeableInterface {
    return new Interface(_abi) as RelayRecipientUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RelayRecipientUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RelayRecipientUpgradeable;
  }
}
