/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdminableUpgradeable } from "./AdminableUpgradeable";
export type { RelayRecipientUpgradeable } from "./RelayRecipientUpgradeable";
